"""Regenerate docs/kpi/kpi_registry.json and docs/kpi/KPI_REGISTRY.md from the code registry.

    python scripts/export_kpi_registry.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from kpi_engine.registry import registry_to_dict  # noqa: E402


def markdown(reg: dict) -> str:
    L = [f"# KPI Registry v{reg['registry_version']}", "",
         "_Generated by `scripts/export_kpi_registry.py` from `backend/kpi_engine/registry.py`. Do not edit by hand._", "",
         "Computation model: every KPI is a **ratio of sums** over validated rows. Rows with missing / invalid inputs are "
         "excluded from numerator **and** denominator and counted. A KPI is `null` (never 0) when its denominator is <= 0.", "",
         "## Datasets", "",
         "| dataset_id | data_source | grain | declared period | file |", "|---|---|---|---|---|"]
    for d in reg["datasets"]:
        L.append(f"| `{d['dataset_id']}` | {d['data_source']} | {d['grain']} | {d['declared_period']} | `{d['file']}` |")
    L += ["", "Datasets never share a population or period; results from different datasets are never merged or compared "
          "(see `check_comparability`).", "", "## KPIs", "",
          "| key | legacy | name | unit | direction | datasets | target |", "|---|---|---|---|---|---|---|"]
    for k in reg["kpis"]:
        tgt = k["target"]["source"] or "none defined"
        L.append(f"| `{k['key']}` | {k['legacy_id']} | {k['display_name']} | {k['unit']} | {k['direction'].replace('_', ' ')} | "
                 f"{', '.join('`'+d+'`' for d in k['datasets'])} | {tgt} |")
    for k in reg["kpis"]:
        L += ["", f"### `{k['key']}`: {k['display_name']}", "", k["description"], "",
              f"- **Formula:** `{k['formula']}`",
              f"- **Unit:** {k['unit']} ({k['unit_label']})",
              f"- **Aggregation:** {k['aggregation']}",
              f"- **Time window:** {k['time_window']}",
              f"- **Min sample before `low_sample` warning:** {k['min_sample']} valid rows",
              f"- **Target:** {k['target']['note'] if k['target']['source'] is None else k['target']['source']}"]
        for ds, cols in k["source_columns"].items():
            L.append(f"- **Source columns (`{ds}`):** {', '.join('`'+c+'`' for c in cols) or 'n/a'}")
        L.append("- **Limitations:**")
        L += [f"  - {x}" for x in k["limitations"]]
    return "\n".join(L) + "\n"


def main() -> None:
    reg = registry_to_dict()
    out = ROOT / "docs" / "kpi"
    out.mkdir(parents=True, exist_ok=True)
    (out / "kpi_registry.json").write_text(json.dumps(reg, indent=2, sort_keys=False, ensure_ascii=False) + "\n")
    (out / "KPI_REGISTRY.md").write_text(markdown(reg))
    print(f"wrote {out/'kpi_registry.json'} and {out/'KPI_REGISTRY.md'} ({len(reg['kpis'])} KPIs, {len(reg['datasets'])} datasets)")


if __name__ == "__main__":
    main()
